# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c1000ced2d085d5344c053ba0fb680ae875dd738e4dc1538bd9d8e80ada26b09c85fa8d206c8acd1c5aa322478ad8dbba5a983c7a4803d39ff624e10baf4c53

test:
  secret_key_base: 6db92728bd0c7c7113692a1aa3e6f9f8b3863b6fa4e53595a6d5a328de3b7860e27ab9d387fa5200eb5d711fefb2b5ac0cd252918a52bd5c0e9dc3aaee7bb4df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
